# Generated by Django 3.2.6 on 2021-09-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='first_name',
            field=models.CharField(default=' ', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='last_name',
            field=models.CharField(default=' ', max_length=12, null=True),
        ),
    ]
