# Generated by Django 3.2.6 on 2021-09-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_extendeduser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=' ', max_length=1, null=True),
        ),
    ]
