# Generated by Django 3.2.6 on 2021-09-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_extendeduser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='gender',
            field=models.CharField(choices=[('NA', 'Select'), ('M', 'Male'), ('F', 'Female')], default=' ', max_length=12, null=True),
        ),
    ]
