# Generated by Django 3.2.6 on 2021-09-15 14:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_extendeduser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None),
        ),
    ]
