# Generated by Django 3.2.6 on 2021-09-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_extendeduser_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='phone_num',
            field=models.CharField(max_length=15),
        ),
    ]
