# Generated by Django 3.2.6 on 2021-09-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_extendeduser_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='email',
        ),
    ]
